architecture: LSTM
cryptocurrency: Bitcoin
hp_lstm_dropout: 0.2
hp_lstm_hidden: 512
hp_lstm_layers: 2
interval: 1d
llm: Orca 2 7B (6-bit)
pp_batch_size: 32
pp_feat_scaler: Standard
pp_sequence_len: 30
pp_target_mode: log_return
pp_target_scaler: None
prompt: Zero-shot
sentiment: Reddit
subreddits: CryptoCurrency
tr_epochs: 100
tr_es_enable: false
tr_es_min_delta: 0.0
tr_es_patience: 20
tr_lr: 0.001
tr_verbose: true
tr_weight_decay: 0.0
